config/routes.rb
TheTask::Application.routes.draw do

  get "dashboard/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match 'players/:player_id/challenges' => 'player_challenges#index'
  match 'games/:game_id/challenges/type_change' => 'challenges#type_change'
  
  resources :entering_messages, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :capturing_codes, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :player_challenges, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :position_confirmation, :only => [:edit, :show, :update], :controller => :player_challenges

 
  resources :rewards do
    get 'collect', :on => :member 
  end
  
  resources :reward_collections, :only => [:index, :show]

  resources :plays, :except => [:destroy, :edit, :new]

  resources :games do
    resources :challenges do
    end
    
 
    get 'activate', :on => :member 
    get 'archive', :on => :member 
  end

  resources :users do
  end
  
  root :to => 'dashboard#index'

  

end

app/models/reward.rb
# Reward model
class Reward < ActiveRecord::Base
  belongs_to :sponsor, :class_name => "User", :foreign_key => :sponsor_id
  belongs_to :creator, :class_name => "User", :foreign_key => :creator_id
  belongs_to :point_kind
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_presence_of :sponsor, :creator, :price_in_points, :point_kind
  has_many :reward_collections
  has_many :winners, :through => :reward_collections
  
  def available?
    (user_limit.nil? || winners.count < user_limit) and 
      (expiration_date.nil? or expiration_date > DateTime.now)
  end

  def available_for?(user)
    available? and user.point_sum(point_kind) >= price_in_points
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = Reward.new
    @point_kinds = PointKind.all.collect {|p| [p.name, p.id] }
    @users = User.all.collect {|p| [p.login, p.id] }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
    @point_kinds = PointKind.all.collect {|p| [p.name, p.id] }
    @users = User.all.collect {|p| [p.login, p.id] }

  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(params[:reward])
    @reward.creator = current_user
    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, :notice => 'Reward was successfully created.' }
        format.json { render :json => @reward, :status => :created, :location => @reward }
      else
        @point_kinds = PointKind.all.collect {|p| [p.name, p.id] }
        @users = User.all.collect {|p| [p.login, p.id] }
        format.html { render :action => "new" }
        format.json { render :json => @reward.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to @reward, :notice => 'Reward was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @reward.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url }
      format.json { head :ok }
    end
  end

  # GET /rewards/1/collect
  def collect
    @reward = Reward.find(params[:id])
    @user = current_user
    respond_to do |format|
      if @user.collect(@reward)
        format.html { redirect_to @reward, :notice => 'Reward was successfully collected.' }
        format.json { head :ok }
      else
        logger.debug @user.errors.full_messages
        format.html { redirect_to @user, :notice => 'Cant collect reward.' }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :price_in_points %>
    <%= f.number_field :price_in_points %>
  </div>

  <div class="field">
    <%= f.label :point_kind %>
    <%= f.select(:point_kind_id, @point_kinds) %>
  </div>

  <div class="field">
    <%= f.label :user_limit %>
    <%= f.number_field :user_limit %>
  </div>

  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.date_select :expiration_date %>
  </div>

  <div class="field">
    <%= f.label :sponsor_id %>
    <%= f.select(:sponsor_id, @users) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/_list.html.erb
<h1> <%= t(:listing_rewards) %> </h1>

<table style="width:100%;">

  <% rewards.each do |reward| %>
  
  <tr>
    <td>
      <%= link_to(reward, :class => "reward_link") do %>
      <%= render :partial => "rewards/reward", :locals => { :reward => reward } %>    
      <% end %>
    </td>
  </tr>

  <% end %>

</table>

app/views/rewards/_reward.html.erb
<div id= "reward_info">
  <div id="reward_image"> <%= image_tag reward.image.url(:thumb)  if reward.image.present? %> </div>
  <div id="reward_price"> <%= reward.price_in_points %> <%= reward.point_kind.name %> </div>
  <div id="reward_description"> <%= reward.description %> </div> 
</div>




 

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

app/views/rewards/index.html.erb
<div id="create_elem">
<%= link_to t(:new_reward), new_reward_path %>
</div>
<%= render :partial => "rewards/list", :locals => { :rewards => @rewards } %> 

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= t(:reward) %></h1>

<ul id="reward_menu">
  <li> <%= link_to 'Edit', edit_reward_path(@reward)  %> </li>
  <li> <%= link_to 'Destroy', @reward, :confirm => 'Are you sure?', :method => :delete %> </li>
  <li> <%= link_to 'Get it', collect_reward_path(@reward), :confirm => 'Realy want this reward?' if @reward.available_for?(current_user) %> </li>
</ul>


<%= render :partial => "rewards/reward", :locals => { :reward => @reward } %>    
      