config/routes.rb
TheTask::Application.routes.draw do

  get "dashboard/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match 'players/:player_id/challenges' => 'player_challenges#index'
  match 'games/:game_id/challenges/type_change' => 'challenges#type_change'
  
  resources :entering_messages, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :capturing_codes, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :player_challenges, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :position_confirmation, :only => [:edit, :show, :update], :controller => :player_challenges

 
  resources :rewards do
    get 'collect', :on => :member 
  end
  
  resources :reward_collections, :only => [:index, :show]

  resources :plays, :except => [:destroy, :edit, :new]

  resources :games do
    resources :challenges do
    end
    
 
    get 'activate', :on => :member 
    get 'archive', :on => :member 
  end

  resources :users do
  end
  
  root :to => 'dashboard#index'

  

end

app/models/game.rb
# Model gry
class Game < ActiveRecord::Base
  attr_protected :status


  # Relations
  belongs_to :creator, :class_name => "User", :foreign_key => :creator_id
  has_many :challenges
  has_many :plays

  # Validations
  validates_presence_of :status, :creator, :title, :description

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  def initialize(params = nil) 
    super(params) 
  end 
  
  state_machine :status, :initial => :new do
    
    state :active do
    end

    state :archived do
    end
  
    event :activate do
      transition :new => :active, :if => :can_activate?
    end
    
    event :archive do
      transition :active => :archived
    end
    
  end

  def can_archive?
    active? and !challenges.empty?
  end

  def can_activate?
    !challenges.empty? and !archived? and !active?
  end
   
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

#  filter_access_to :edit

  # GET /games
  # GET /games.json
  def index
    @games = Game.paginate(:page => params[:page], :per_page => 3)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    @game.creator = current_user
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, :notice => 'Game was successfully created.' }
        format.json { render :json => @game, :status => :created, :location => @game }
      else
        logger.debug @game.errors.messages
        format.html { render :action => "new" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])
    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, :notice => 'Game was successfully updated.' }
        format.json { head :ok }
      else
        logger.debug @game.errors.messages
        format.html { render :action => "edit" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /games/1/activate
  def activate
    @game = Game.find(params[:id])
    respond_to do |format|
      if @game.activate
        format.html { redirect_to @game, :notice => 'Game was successfully activated.' }
        format.json { head :ok }
      else
        format.html { redirect_to @game, :notice => 'Cannot activate this game.' }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end


  # GET /games/1/archive
  def archive
    @game = Game.find(params[:id])
    respond_to do |format|
      if @game.archive
        format.html { redirect_to @game, :notice => 'Game was successfully archived.' }
        format.json { head :ok }
      else
        format.html { redirect_to @game, :notice => 'Game cannot be archived.' }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:game_title) %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit :id => "commit_game" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id= "game_info">
  <div id="game_image"> <%= image_tag game.image.url(:thumb) %> </div>
  <div id="game_title"> <%= game.title %> </div>
  <div id="game_description"> <%= game.description %> </div>
</div>

app/views/games/_info.html.erb
<%= link_to(game) do %>
<div id= "game_info">
  <div id="game_image"> <%= image_tag game.image.url(:thumb) %> </div>
  <div id="game_title"> <%= game.title %> </div>
  <div id="game_description"> <%= game.description %> </div>
</div>
<% end %>

app/views/games/_list.html.erb
<h1> <%= t(:games) %></h1>

<table style="width:100%;">
  <% if games.count > 0 %>
  <% games.each do |game| %>
  <tr>
    <td>
      <%= link_to(game, :class => "game_link") do %>
      <%= render :partial => "games/game", :locals => { :game => game } %>    
      <% end %>
    </td>
  </tr>
  <% end %>
  <% else %>
  Brak dostępnych gier
  <% end %>
</table>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div id="create_elem">
<%= link_to t(:new_game), new_game_path %>
</div>

<%= render :partial => "games/list", :locals => { :games => @games } %> 

<%= will_paginate @games %>

app/views/games/new.html.erb
<h1> <%=t(:new_game) %></h1>

<%= render 'form' %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= t(:game) %></h1>

<ul id="game_menu">
  <li> <%= link_to t(:edit), edit_game_path(@game)  if @game.new? %> </li>
  <li> <%= link_to t(:delete), @game, :confirm => t(:are_you_sure), :method => :delete if @game.new? %>  </li>
  <li> <%= link_to t(:archive), archive_game_path(@game) if @game.can_archive?  %> </li> 
  <li> <%= link_to t(:activate), activate_game_path(@game) if @game.can_activate?  %>  </li>
  <li> <%= link_to t(:play), plays_path(:play => {:player_id => current_user, :game_id => @game.id}), :method => :post if @game.active? %>  </li>
</ul>


<%= render :partial => "games/game", :locals => { :game => @game } %>    

<%= render :partial => "challenges/list", :locals => { :challenges => @game.challenges, :game => @game } %>