config/routes.rb
TheTask::Application.routes.draw do

  get "dashboard/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match 'players/:player_id/challenges' => 'player_challenges#index'
  match 'games/:game_id/challenges/type_change' => 'challenges#type_change'
  
  resources :entering_messages, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :capturing_codes, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :player_challenges, :only => [:edit, :show, :update], :controller => :player_challenges
  resources :position_confirmation, :only => [:edit, :show, :update], :controller => :player_challenges

 
  resources :rewards do
    get 'collect', :on => :member 
  end
  
  resources :reward_collections, :only => [:index, :show]

  resources :plays, :except => [:destroy, :edit, :new]

  resources :games do
    resources :challenges do
    end
    
 
    get 'activate', :on => :member 
    get 'archive', :on => :member 
  end

  resources :users do
  end
  
  root :to => 'dashboard#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheTask</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>

</head>

<body>

<ul id="small_menu">
  <% if current_user %>
  <li> <%= link_to t(:logout), destroy_user_session_path, :method => :delete %> </li>
  <li> <%= link_to t(:me, :login => current_user.login), user_path(current_user) , :class => is_active?('', 'users')  %>  </li>
  <% else %>
  <li> <%= link_to "sign in with google", user_omniauth_authorize_path(:google) %> </li>
  <% end %>
</ul>

<ul id="main_menu">
 <li> <%= link_to t(:rewards), rewards_path, :class => is_active?('index', 'rewards') %> </li>
 <li> <%= link_to t(:plays), plays_path, :class => is_active?('index', 'plays') %>  </li>
 <li> <%= link_to t(:games), games_path, :class => is_active?('index', 'games') %>  </li>
 <li> <%= link_to t(:home), '/', :class => is_active?('index', 'dashboard')  %> </li>
</ul>


<div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>

</body>
</html>